#!/bin/bash

config_db(){
    APEX_SCHEMA=`${ORACLE_HOME}/bin/sqlplus -s -l sys/${PASS} AS SYSDBA <<EOF
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT ao.owner FROM all_objects ao WHERE ao.object_name = 'WWV_FLOW' AND ao.object_type = 'PACKAGE' AND ao.owner LIKE 'APEX_%';
EXIT;
EOF`
    echo "Use APEX schema ${APEX_SCHEMA}"

    echo "Set password lifetime limit"
    echo "ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;" | ${ORACLE_HOME}/bin/sqlplus -s -l sys/${PASS} AS SYSDBA

    ${ORACLE_HOME}/bin/sqlplus -s -l sys/${PASS} AS SYSDBA <<EOF
ALTER SESSION SET CURRENT_SCHEMA=${APEX_SCHEMA};
BEGIN
APEX_INSTANCE_ADMIN.SET_PARAMETER('DISABLE_ADMIN_LOGIN', 'N');COMMIT;
APEX_INSTANCE_ADMIN.SET_PARAMETER('ACCOUNT_LIFETIME_DAYS', '999');COMMIT;
APEX_INSTANCE_ADMIN.SET_PARAMETER('EXPIRE_FND_USER_ACCOUNTS', 'N');COMMIT;
APEX_INSTANCE_ADMIN.SET_PARAMETER('LOGIN_THROTTLE_DELAY', 0);COMMIT;
APEX_INSTANCE_ADMIN.SET_PARAMETER('STRONG_SITE_ADMIN_PASSWORD', 'N');COMMIT;
END;
EXIT;
EOF
    
}


echo "Configure DB: ${ORACLE_SID}"
. /home/oracle/.bash_profile
config_db
cd /
